### ISSUE TITLE
Lmao rekt for you pytuz

### ISSUE THREAD

**Issue by pytuz** [TimeTopia/GrowTale-Source-Full-folder#1]
ahahhaa https://www.virustotal.com/gui/file/93be3e84d252e1fd1cdc5c6cbc22521c902e47871c4a8c91871ed30cb38b3dfb/detection
https://www.virustotal.com/gui/file/93be3e84d252e1fd1cdc5c6cbc22521c902e47871c4a8c91871ed30cb38b3dfb/detection
https://www.virustotal.com/gui/file/93be3e84d252e1fd1cdc5c6cbc22521c902e47871c4a8c91871ed30cb38b3dfb/detection
https://www.virustotal.com/gui/file/93be3e84d252e1fd1cdc5c6cbc22521c902e47871c4a8c91871ed30cb38b3dfb/detection

16 detects, includes viruses, trojan, malware lololo

**Comment by pytuz** [comment]
![image](https://user-images.githubusercontent.com/62787162/81878025-faa32500-95b0-11ea-85ce-0fce24c5867d.png)

**Comment by pytuz** [comment]
![image](https://user-images.githubusercontent.com/62787162/81878039-02fb6000-95b1-11ea-9b04-a8e7964d69b4.png)

**Comment by pytuz** [comment]
tRoJaN fOr KiDDoS
tElL hIM tHT

**Comment by TimeTopia** [comment]
U kid yr a kid, trying to make me look bad butbur a failure mate

**Comment by TimeTopia** [comment]
Mom me nub

**Comment by pytuz** [comment]
ahahha
